name: disaster_mapper
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bottom_nav_bar: ^1.0.3
  cloud_firestore: ^4.8.3
  cupertino_icons: ^1.0.2
  excel: ^2.1.0
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.2
  geolocator: ^8.0.1
  get: 
  google_fonts: ^5.1.0
  google_maps: ^6.3.0
  google_maps_flutter: ^2.3.1
  image_picker: ^1.0.1
  intl: ^0.18.1
 
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
